export type WordType = {
  en?: string;
  word?: string;
  participles?: string[];
  breakdown?: [string, string][];
  note?: string;
};

export const wordList: Record<string, WordType> = {
  // 콜라: { en: 'Cola' },
  좋아해: { word: '좋아하다' },
  // 별로: { en: 'not really' },
  예전에: { word: '예전', participles: ['에'] },
  // 너무: { en: 'too' },
  // 많이: { en: 'many/much' },
  마셨는데: { word: '마시다', participles: ['었', '는데'] },
  // 마셨는데: { en: 'when I drink' },
  // 수업: { en: 'class' },
  시간에: { word: '시간', participles: ['에'] },
  트림이: { word: '트림', participles: ['이'] },
  멈추질: { word: '멈추다', participles: ['지'] },
  않았어: { word: '않다', participles: ['았'] },
  // 으엑: { en: 'eww' },
  징그러워: { word: '징그럽다' },

  반에서: {
    en: 'in the class',
    breakdown: [
      ['반', 'class'],
      ['에서', 'in'],
    ],
  },
  '1등인데': {
    en: 'since you are first place',
    breakdown: [
      ['1등 (일등)', 'first place'],
      ['이다', 'are'],
      ['ㄴ데', 'since'],
    ],
  },
  // 이번: { en: 'this time' },
  // 시험: { en: 'exam' },
  어땠어: { en: 'how was' },
  음: { en: 'um' },
  // 꽤: { en: 'quite' },
  쉬웠던: { en: 'was easy' },
  같아: { en: 'seems / I think' },
  기본만: {
    en: 'just the basics',
    breakdown: [
      ['기본', 'basics'],
      ['만', 'just'],
    ],
  },
  알면: {
    en: 'if you know',
    breakdown: [
      ['알다', 'know'],
      ['면', 'if'],
    ],
  },
  다: { en: 'all' },
  비슷비슷하잖아: {
    en: 'pretty similar, right?',
    breakdown: [
      ['비슷', 'similar'],
      ['비슷하', 'be similar'],
      ['잖아', 'right?'],
    ],
  },
  난: { en: 'I' },
  어렵던데: {
    en: 'found it hard',
    breakdown: [
      ['어렵다', 'be hard'],
      ['던', '(something in the past)'],
      ['데', 'as I recall'],
    ],
  },
  아: { en: 'ah' },
  // 진짜: { en: 'really' },
  머리카락이: {
    en: 'hair',
    breakdown: [
      ['머리', 'head'],
      ['카락', 'hair'],
    ],
  },
  // 왜: { en: 'why' },
  얼굴을: { en: 'face' },
  가려: { en: 'cover/hide' },
  // 요즘: { en: 'these days' },
  스타일이야: {
    en: 'is style',
    breakdown: [
      ['스타일', 'style'],
      ['이야', 'is'],
    ],
  },
  나: { en: 'I' },
  어때: { en: 'how is it' },
  // 공포: { en: 'horror' },
  // 영화: { en: 'movie' },
  // 스타일: { en: 'style' },
  아니야: { en: 'is it not?' },
  어: { en: 'oh' },
  망했나: {
    en: 'did I fail?',
    breakdown: [
      ['망하다', 'fail'],
      ['했', 'did (past)'],
      ['나', '(question)'],
    ],
  },
  // 그래서: { en: 'so' },
  // 오늘: { en: 'today' },
  지각했어: { en: 'was late' },
  할머니가: { en: 'grandmother' },
  아프셔서: {
    en: 'because sick',
    breakdown: [
      ['아프다', 'be sick'],
      ['셔', 'was'],
      ['서', 'because'],
    ],
  },
  병원에: {
    en: 'to the hospital',
    breakdown: [
      ['병원', 'hospital'],
      ['에', 'to'],
    ],
  },
  // 같이: { en: 'together' },
  갔거든: {
    en: 'went',
    breakdown: [
      ['가다', 'to go'],
      ['았', '(past) ~ went'],
      ['거든', 'because'],
    ],
  },
  헐: { en: 'whoa' },
  아니: { en: 'not really' },
  // 그냥: { en: 'just' },
  // 늦잠: {
  //   en: 'oversleep',
  //   breakdown: [
  //     ['늦', 'late'],
  //     ['잠', 'sleep'],
  //   ],
  // },
  잤어: {
    en: 'slept',
    breakdown: [
      ['자다', 'to sleep'],
      ['았다', '(past) ~ slept'],
    ],
    note: "잠 자 together means 'to sleep'",
  },

  속보입니다: {
    en: 'breaking news',
    breakdown: [
      ['속보', 'breaking new'],
      ['입니다', 'is'],
    ],
  },
  방금: { en: 'just now' },
  전: { en: 'before' },
  남자: { en: 'man' },
  화장실에서: {
    en: 'in the bathroom',
    breakdown: [
      ['화장실', 'bathroom'],
      ['에서', 'in'],
    ],
  },
  비누통이: { en: 'soap bottle' },
  폭발했습니다: { en: 'exploded' },
  현장은: { en: 'the scene' },
  완전: { en: 'total' },
  난장판이에요: {
    en: 'is chaos',
    breakdown: [
      ['난장판', 'chaos'],
      ['이에요', 'is'],
    ],
  },
  목격자들에: { en: 'witnesses' },
  따르면: { en: 'according to' },
  비누가: { en: 'soap' },
  벽: { en: 'wall' },
  거울: { en: 'mirror' },
  심지어: { en: 'even' },
  천장까지: {
    en: 'to the ceiling',
    breakdown: [
      ['천장', 'ceiling'],
      ['까지', 'until'],
    ],
  },
  튀었다고: {
    en: 'said it splashed',
    breakdown: [
      ['튀었', 'splashed'],
      ['다고', 'said'],
    ],
    note: "~다고 합니다 together means 'said'",
  },
  합니다: { en: 'did' },
  선생님들도: {
    en: 'even the teachers',
    breakdown: [
      ['선생님들', 'teachers'],
      ['도', 'even'],
    ],
  },
  어리둥절한: { en: 'confusing' },
  상황이고: {
    en: 'the situation is',
    breakdown: [
      ['상황', 'situation'],
      ['이고', 'is'],
    ],
  },
  아무도: { en: 'no one' },
  자백하지: { en: 'confess', note: "~하지 않다 together means 'do not'" },
  않고: { en: 'did not' },
  있어요: { en: 'doing', note: "~고 있다 together means 'doing'" },
  과연: { en: 'indeed' },
  다음엔: { en: 'next' },
  무슨: { en: 'what kind of' },
  일이: { en: 'thing/event' },
  벌어질까요: { en: 'will happen' },

  중요: { en: 'important' },
  과학실: {
    en: 'science room',
    breakdown: [
      ['과학', 'science'],
      ['실', 'room'],
    ],
  },
  앞에: { en: 'in front of' },
  갈매기: { en: 'seagull' },
  떼가: { en: 'a flock of' },
  나타났습니다: { en: 'has appeared' },
  학생들: { en: 'students' },
  손에서: {
    en: 'from hands',
    breakdown: [
      ['손', 'hand'],
      ['에서', 'from'],
    ],
  },
  물건을: { en: 'things' },
  훔쳐가고: { en: 'steal' },
  어떤: { en: 'some' },
  여자: { en: 'woman/girl' },
  학생은: { en: 'student' },
  갈매기한테: {
    en: 'by a seagull',
    breakdown: [
      ['갈매기', 'seagull'],
      ['한테', 'by/from'],
    ],
  },
  안경까지: {
    en: 'even glasses',
    breakdown: [
      ['안경', 'glasses'],
      ['까지', 'even'],
    ],
  },
  뺏겼대요: { en: 'snatched' },
  밖에: { en: 'outside' },
  나가야: {
    en: 'must go out',
    breakdown: [
      ['나가다', 'go out'],
      ['야', 'must'],
    ],
  },
  한다면: {
    en: 'if you do',
    breakdown: [
      ['한다', 'do'],
      ['면', 'if'],
    ],
  },
  조심하세요: { en: 'be careful' },

  임돈기: { en: 'DonKi Lim' },
  리포팅: { en: 'reporting' },
  교장: { en: 'principal' },
  선생님께서: { en: 'to the teachers' },
  큰: { en: 'big' },
  발표를: { en: 'announcement' },
  하신다고: { en: 'said' },
  무엇일까요: { en: 'what?' },

  입니다: { en: 'is' },
  선생님이: { en: 'teachers' },
  말씀하셨어요: { en: 'told' },
  오늘부터: { en: 'from today' },
  모두: { en: 'all' },
  긴: { en: 'long' },
  양말을: { en: 'socks' },
  신어야: { en: 'must wear' },
  한다고: { en: 'said' },
  이: { en: 'this' },
  새로운: { en: 'new' },
  유행: { en: 'fashion' },
  어떻게: { en: 'how' },
  될까요: { en: 'will happen?' },

  다시: { en: 'again' },
  전합니다: { en: 'telling' },
  속보: { en: 'newsflash' },
  한: { en: 'one' },
  학생이: { en: 'student' },
  빨간색: { en: 'red' },
  신고: { en: 'wearing' },
  학교에: { en: 'at school' },
  왔습니다: { en: 'came' },
  그게: { en: 'this' },
  가진: { en: 'have' },
  유일한: { en: 'only' },
  양말: { en: 'socks' },
  이라네요: { en: 'are' },
  앞으로: { en: 'after this' },

  여학생들이: { en: 'female students' },
  검은색: { en: 'black' },
  스타킹도: { en: 'stockings also' },
  양말로: { en: 'socks' },
  인정되는지: { en: 'recognise' },
  묻고: { en: 'ask' },
  있습니다: { en: '-ing' },
  선생님들은: { en: 'the teachers' },
  당황해서: { en: 'being embarrassed' },
  대답을: { en: 'a reply' },
  못: { en: 'cannot' },
  하고: { en: 'do' },
  있네요: { en: '-ing' },

  충격적인: { en: 'shocking' },
  시위: { en: 'demonstration' },
  많은: { en: 'many' },
  학생들이: { en: 'students' },
  아예: { en: 'completely' },
  신지: { en: 'wear' },
  등교했습니다: { en: 'go to school' },
  대신: { en: 'instead' },
  교장실: { en: "principal's office" },
  앞에서: { en: 'outside of' },
  더러운: { en: 'dirty' },
  더미가: { en: 'pile' },
  발견되었습니다: { en: 'was discovered' },

  발표하셨습니다: { en: 'was announced' },
  이제: { en: 'now' },
  양말은: { en: 'socks' },
  길지: { en: 'long' },
  않아도: { en: "don't have to" },
  된다고: { en: "said it's okay" },
  학생들은: { en: 'students' },
  성공적인: { en: 'successful' },
  승리를: { en: 'victory' },
  축하하며: { en: 'congratulate and' },
  환호하고: { en: 'cheer' },

  뜨거운: { word: '뜨거다' },
  게: { word: '것' },
  좋아요: { word: '좋아하다' },
  따뜻하면: { word: '따뜻하다', participles: ['면'] },
  풀려요: { word: '풀리다' },
  춥잖아요: { word: '춥다', participles: ['잖아'] },

  시원하면: { word: '시원하다', participles: ['면'] },
  좋아져요: { word: '좋아하다' },
  시원하게: { word: '시원하다' },
  느껴지죠: { word: '느끼다' },

  넣어서: { word: '넣다', participles: ['어서'] },
  드세요: { word: '드시다' },
  아니요: { word: '아니다' },
  달아요: { word: '달다' },
  마셔요: { word: '마시다' },
  쓰잖아요: { word: '쓰다', participles: ['잖아'] },
  달콤한: { word: '달콤하다' },
  거: { word: '것' },
  없으면: { word: '없다', participles: ['면'] },
  살아요: { word: '살다' },
};
